### ISSUE TITLE
basic bash-like path expansion

### ISSUE THREAD

**Issue by mcginty** [mcginty/shoop#22]
expand `~` to $HOME, `~+` to process pwd

✨stretch goal expand `~user` to a user's $HOME

**Comment by mcginty** [comment]
https://github.com/mcginty/shoop/commit/60d32f3d3b7df795c62310c77d7b3949470ae4de

**Comment by zmanian** [comment]
Just some thoughts, I once was involved in a alternate shell project where we re-implemented the entire shell expansion rules from BASH in a fully compatible way. It was bigish but not overwhelming.

Here is some moderately more comprehensive Rust code for shell expansion.
https://github.com/netvl/shellexpand

What would be the consequences of invoking a shell to run the command insider server side?

**Comment by mcginty** [comment]
Eh, mostly just complexity and portability (which the current implementation also suffers from). But really that's the only way to be compatible with all the expansions. Not even that shellexpand library supports ~user.

Overall we're kind of lucky. Because of the authentication, our security model is a little forgiving in this department. The user trusts the server input, the server trusts the user input. We just have to make sure shoop doesn't do unexpected stuff on either side, but as long as the authentication isn't broken there's not really any untrusted input data.
