### ISSUE TITLE
warn on weak ssh ciphersuites

### ISSUE THREAD

**Issue by mcginty** [mcginty/shoop#32]
using `-v` in our SSH command, it's within our reasonable capacity to detect and warn on a user's ssh client/server stabbing them in the foot.

**Comment by mcginty** [comment]
took a slightly different (better) approach, where you can tell SSH to force a certain allowed ciphersuite. If that command fails, it will warn and then fall back (for now). I think in the future it shoud instead fail unless a "--allow-weak-ssh-ciphers" flag arg is set.

**Comment by eedeep** [comment]
Hi there....just wondering if said `--allow-weak-ssh-ciphers` flag actually exists in the latest version? I can't see it anywhere.

**Comment by mcginty** [comment]
@eedeep The plan is to add `allow-weak-ssh-ciphers` when the change to fail on weak ciphers happens. Right now it just warns but continues.

I'd love to dedicate a week or so to improving shoop further, it hasn't gotten enough love lately :).

**Comment by eedeep** [comment]
Ah k right. I am slightly confused though, what is this error condition about then? https://github.com/mcginty/shoop/blob/master/src/ssh.rs#L120 Because I ran into that and didn't know how to get around/past it.

**Comment by mcginty** [comment]
@eedeep that's a message formatted as an error in the console output, but not a panic

**Comment by mcginty** [comment]
I've been working on bringing a clean implementation of the Noise Protocol to Rust, and I'm hoping to switch `shoop` over to that more peer-reviewed protocol after this is done. (https://github.com/mcginty/snow)
