### ISSUE TITLE
Should I use "Shoop" to upload photos in webp format in the size of 10 kb to 30 kb to the Ubuntu VPS server, or should I look for another solution?

### ISSUE THREAD

**Issue by oG14108149527Exl0Ftr7sY** [mcginty/shoop#41]
<h2>1</h2>
Thanks for the project: "Shoop, Scp has a run-in with Mosh (alpha)"

https://github.com/mcginty/shoop

The Shoop project looks incredibly exciting.
In the past, I have good experience with Mosh.

<h2>2.</h2>
I am planning a trip where I need to use satellite to update WordPress.

<h2>3.</h2>
Want to publish to WordPress with WP-CLI - https://wp-cli.org - during the journey
I use an Intel Macbook and publish to a Linux Ubuntu 20.04 VPS server 

<h2>4.</h2>
During large parts of the journey, there is no mobile phone coverage.

<h2>5.</h2>
Want to publish using the satellite phone Iridium 9555 and Redport Optimizer.

https://www.iridium.com/products/iridium-9555/

https://www.redportglobal.com/marine-satellite-internet-firewall-routers/router-models/optimizer-satellite-firewall-and-wi-fi-hotspot/

<h2>6.</h2>
The challenge is that the speed over satellite is 2,400 bit / s (or baud):

http://www.mailasail.com/Support/Iridium-Bandwidth

<h2>7.</h2>
I have previously had good experiences with Mosh.
I want to use Mosh together «WP-CLI» to update WordPress and send e-mails with the command line «mailx» e-mail client on this trip.

<h2>8.</h2>
Need a solution for uploading photos in webP format and size 10kb to 30kb as described here:

http://www.globalmarinenet.com/how-to-send-photos-over-your-satellite-phone/

<h2>9.</h2>
<h3>My concern is the statement:</h3>

«This [[Shoop]](https://github.com/mcginty/shoop) is so incredibly alpha. Not alpha-like how fraternities use it. Alpha like unverified.»

<h2>QUESTION:</h2>

Should I use "Shoop" to upload photos in webP format in the size of 10 kb to 30 kb to the Ubuntu VPS server, or should I look for another solution?

**Comment by mcginty** [comment]
Hey there - I'd stick to rsync for something like that, unfortunately I haven't been maintaining shoop and it's in desperate need of a rewrite some time.
