### ISSUE TITLE
write tests i guess

### ISSUE THREAD

**Issue by mcginty** [mcginty/shoop#8]

**Comment by eminence** [comment]
It might be cool to figure out how to write tests that simulate a lossy connection, to confirm shoops performance over these types of links.  since everything is UDP based, maybe a simple "proxy" that will blindly forward UDP packets from src to dst, but drop a configurable percentage of them

**Comment by mcginty** [comment]
@eminence that would be the bee's knees.

The closest thing I can see is [netem](https://wiki.linuxfoundation.org/networking/netem) for linux and [clumsy](https://github.com/jagt/clumsy) for Windows.

**Comment by eminence** [comment]
To be clear for the record -- not all tests are written, but start has been made.  It's an ongoing effort.
